baseURL = "https://cascadiadataalliance.org/"
externalURL = "https://www.fredhutch.org/en/about/about-the-hutch/institutional-partners-collaborations/cascadia-data-alliance.html"
# baseURL = "https://fredhutch.github.io/cascadiadataalliance.org/"
languageCode = "en-us"
title = "Cascadia Data Alliance"
theme = "vex-hugo"
publishDir = "docs"

[params]
    project_name = "The Cascadia Data Alliance"
    project_tagline = "Data Science Collaborations"
    description = ""

  # Put your custom stylesheets and scripts
  custom_stylesheets = []
  custom_scripts = []

  # Additional meta
  [[params.meta]]
    name = "The Cascadia Data Alliance"
    description = "Data Science Collaborations"

  # Navigation bar informations
  [params.navbar]
     logo = "images/Cascadia_Horiz_Logo.svg"
    [[params.navbar.menu]]
      link = "#"
      text = "HOME"
    [[params.navbar.menu]]
      link = "#focuses"
      text = "Focuses"
    [[params.navbar.menu]]
      link = "#about"
      text = "About"
    [[params.navbar.menu]]
      link = "#try"
      text = "Demo"

  # Header
  [params.header]
    title = "The Cascadia Data Alliance"
    text = "The Cascadia region of North America is home to some of the world’s leading technology, research, and medical organizations. Large amounts of biomedical research data are being generated in this geographical area that could be used to support accelerated research if shared effectively. The Cascadia Data Alliance, spearheaded by Fred Hutchinson Cancer Research Center, is developing a data sharing ecosystem to position the region as a global leader in data-driven biomedical research and healthcare, now and into the future."
  [params.header.button]
      link = "https://www.fredhutch.org/en/about/about-the-hutch/institutional-partners-collaborations/cascadia-data-alliance.html"
      text = "More Information"

  # Features
  [params.features]
    title = "Our Core Focus Areas"
##    [params.features.image]
##      path = "images/watch-2.png"
##      alt = "Watch"
    # Menu at the left of the image
    [[params.features.left]]
#      icon = "tf-ion-ios-alarm-outline"
      title = "Data Discovery"
      text = "Enable sharing of metadata (descriptive information about underlying data) so researchers can find interesting and unique datasets more quickly."
    # Center box
    [[params.features.center]]
#      icon = "tf-ion-ios-alarm-outline"
      title = "Privacy Preservation"
      text = "Testing and deploying technological methods to enhance privacy preservation in health research data, including differential privacy and synthetic data generation."
    # Menu at the right of the image
    [[params.features.right]]
#      icon = "tf-ion-ios-alarm-outline"
      title = "Data Sharing"
      text = "Streamline existing mechanisms related to governance and generate common approaches for data sharing agreements."

  # About
  [params.promo]
    title = "About the Alliance"
    text = "The Cascadia Data Alliance is being spearheaded by the Fred Hutchinson Cancer Research Center with generous funding and in-kind support from Microsoft. Collaborating institutions include BC Cancer, the Knight Cancer Institute at Oregon Health & Science University, the University of British Columbia Data Science Institute, and the University of Washington eScience Institute."
    [params.promo.image]
      path = "images/Cascadia_Region.jpeg"
      alt = "Watch"

##  [params.feature_list]
##    title = "Why Choose Apple Watch"
##    [[params.feature_list.items]]
##      image = "images/showcase/showcase-4.png"
##      title = "Lorem ipsum dolor sit amet."
##      text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate, sed, assumenda. Tenetur sed esse, voluptas voluptate est veniam numquam, quis magni. Architecto minus suscipit quas, quo harum deserunt consequatur cumque!"
##      button_link = ""
##      button_text = "Check Features"
##    [[params.feature_list.items]]
##      image = "images/showcase/showcase-3.png"
##      title = "Lorem ipsum dolor sit amet."
##      text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate, sed, assumenda. Tenetur sed esse, voluptas voluptate est veniam numquam, quis magni. Architecto minus suscipit quas, quo harum deserunt consequatur cumque!"
##      button_link = ""
##      button_text = "Check Features"

##  [params.gallery]
##    title = "Checkout some amazing Shorts"
##    # Set the image directory to use as base
##    directory = "images/showcase"
##    # Set the images to show in the gallery
##    images = ["showcase-1.png", "showcase-2.png", "showcase-3.png", "showcase-4.png", "showcase-5.png", "showcase-6.png", "showcase-7.png", "showcase-8.png"]

  # Demo
  [params.call_to_action]
    title = "Check out our Subscribed Search Demo"
    text = "TagSearch"
#    placeholder = "Your Email Address Here"
    link = "https://tagsearch.cascadiadataalliance.org"
    button_text = "TagSearch"

##  [params.testimonials]
##    title = "Watch Review"
##    [[params.testimonials.blocks]]
##      text = "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents."
##      name = "Jonathon Andrew"
##      position = "CEO, Themefisher"
##      image = "images/avater.png"
##    [[params.testimonials.blocks]]
##      text = "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents."
##      name = "Jonathon Andrew"
##      position = "CEO, Themefisher"
##      image = "images/avater.png"
##    [[params.testimonials.blocks]]
##      text = "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents."
##      name = "Jonathon Andrew"
##      position = "CEO, Themefisher"
##      image = "images/avater.png"
##    [params.testimonials.button]
##      link = ""
##      text = "Grab You Product Now"

  # Footer uses navbar data
